### ISSUE TITLE
server implementation

### ISSUE THREAD

**Issue by GlenDC** [ccding/go-stun#21]
Currently this package only contains the Client implementation, would a Server implementation be within the Scope of this package, I certainly would hope it does?

I'm asking as I might be interested to have this working in a P2P network, where a peer would be both a client and server, so having a server implementation ready in Golang, would help a lot with that?

I'm prepared to do the work for this, would just need to know if:

+ this is within the scope of this package;
+ this is actually something feasible;

**Comment by shurcooL** [comment]
Is there a benefit in having the server and client in same package, instead of just having the server available in a separate package?

**Comment by GlenDC** [comment]
Not too much benefit, but I don't see why it would be in a separate package. Certainly all the protocol related code and constants could be shared.

**Comment by jannson** [comment]
@GlenDC you can try this package in server side: https://github.com/pixelbender/go-stun
I have test it, it works ok. And compitible with this client side.

**Comment by ernado** [comment]
Hi @GlenDC, please try the [gortc/gortcd](https://github.com/gortc/gortcd), also written in go and should work for STUN and TURN.

I also think that the STUN server implementation is out of scope of current package.
