### ISSUE TITLE
Please version go-stun

### ISSUE THREAD

**Issue by aviau** [ccding/go-stun#22]
Hello,

Could you please tag this repository?

I am the Debian Maintainer for this project and tags would help Debian keep up with new releases/bugfixes.

See:
- http://semver.org/
- http://dave.cheney.net/2016/06/24/gophers-please-tag-your-releases

**Comment by ccding** [comment]
will do it, thanks for the suggestion

**Comment by xiang90** [comment]
check https://github.com/ccding/go-stun/releases/tag/0.1.0

closing
