### ISSUE TITLE
UDP hole punching question

### ISSUE THREAD

**Issue by andrewarrow** [ccding/go-stun#23]
thanks for this repo, just what I was looking for.

Question on UDP hole punching: is this something the big peer networks do reliable to the point they don't have to send people to https://portforward.com or do the majority of peer to peer networks not use UDP hole punching because it isn't 100% reliable and having the user go into their router and make a real open port is always a more reliable solution?

**Comment by AudriusButkevicius** [comment]
Your question is incredibly convoluted and very long, so it's not clear what you are asking for.
It's best if you break this down into multiple questions.
