### ISSUE TITLE
stun punching invalid a few minutes later

### ISSUE THREAD

**Issue by nkbai** [ccding/go-stun#28]
if I use the punchd port as a udp server ,a few minutes later, it will fail.
it needs a keep alive method. 
the keepalive method can not cooperate with a server connection, because when keep alive called, this method will send and receive  packet.
generally , there only one postion for receiving packet!

**Comment by AudriusButkevicius** [comment]
You need to implement this yourself and do filtering, I don't think there is a way around it.

**Comment by nkbai** [comment]
do you mean that  impement another keepalive method myself?

**Comment by AudriusButkevicius** [comment]
Well, you can either use the existing one provided by the library, and filter out packets coming back, or do an application level keepalive, by trying to reconnect to some node every 24seconds.

**Comment by nkbai** [comment]
for the first way:
but there are two problem
1: i can filter packets for comming back, but your keepalive method change the property of the connection, it calls setreaddeadline
2. the keepalive method will receive many my own packets , which makes my protocol error.

that's why i  want  sending  stun request only

**Comment by nkbai** [comment]
the second way is ok,
but there is no relation with this keepalive method.

**Comment by AudriusButkevicius** [comment]
But you can already implement keepalives in your own application, sending a random packet somewhere, or doing it at your protocol level.
