### ISSUE TITLE
Naming of NATSymmetricUDPFirewall

### ISSUE THREAD

**Issue by olifre** [ccding/go-stun#33]
It took me a while to understand that `NATSymmetricUDPFirewall` actually means `Symmetric UDP Firewall` without any actual NAT being involved (as is also shown in the RFC and the flow chart in https://github.com/ccding/go-stun/blob/master/stun/discover.go ). 

I wonder whether this constant should be renamed / aliased to `SymmetricUDPFirewall` to better clarify that this is very different from `NATSymmetric` ?

**Comment by xiang90** [comment]
@olifre 

can you send a PR to fix this?

**Comment by olifre** [comment]
@xiang90 In principle yes, but there are two problems:
- I don't know if there should be an alias (for a while?) to not break API compatibilitiy with other users (e.g. syncthing) hard. 
- I basically only know Go well enough to read it, so I would only be able to do a search / replace (but well, that's really sufficient here I think :wink: ).

**Comment by ccding** [comment]
closing this since no PR. The name indicates the meaning: https://github.com/ccding/go-stun/blob/master/stun/const.go#L62

**Comment by olifre** [comment]
@ccding  I could of course do a PR on this, but I'd love feedback first if an alias should be kept and if there's general agreement on a new name. 
The current name seems irritating even though the description is clear. Since the broken name `NATSymmetricUDPFirewall` has already lead to confusion in Syncthing (which did consider this a NAT, but it's completely unrelated), I don't think it's good to keep that.

**Comment by ccding** [comment]
@olifre Can you have a look at #34 ?
