### ISSUE TITLE
Does it support ipv6?

### ISSUE THREAD

**Issue by dosgo** [ccding/go-stun#41]
Does it support ipv6? Although our ipv6 does not have a nat, the superior route has a firewall, and the inbound is completely blocked, and because it is a 4G network, the firewall settings cannot be changed. I am wondering whether stun can be used in ipv6.

**Comment by ccding** [comment]
Unfortunately we don't have an RFC for that

**Comment by dosgo** [comment]
Makes sense. It seems to be the only reality

**Comment by dosgo** [comment]
Makes sense. It seems to be the only reality
