### ISSUE TITLE
NAT Type: UDP is blocked

### ISSUE THREAD

**Issue by yl604636754** [ccding/go-stun#45]
编译运行之后，总报NAT Type: UDP is blocked

**Comment by Chase-Fu** [comment]
我也到这个问题，怎么处理

**Comment by xlch88** [comment]
如果你是中国大陆用户，请使用国内stun服务器

这是我的私人服务器：stun.qwq.pink:3478

**Comment by Chase-Fu** [comment]
请问你搭建得私人服务器是用coturn么？是不是一定要有域名服务端？我看代码里限制了-s只能用域名？服务端不一定需要双公网ip把 我想自己搭一个server端给点意见谢谢了！

**Comment by Chase-Fu** [comment]
> 如果你是中国大陆用户，请使用国内stun服务器
> 
> 这是我的私人服务器：stun.qwq.pink:3478

请问你搭建得私人服务器是用coturn么？是不是一定要有域名服务端？我看代码里限制了-s只能用域名？服务端不一定需要双公网ip把 我想自己搭一个server端给点意见用哪个开源组件公网IP域名要求 谢谢了！
