### ISSUE TITLE
[Feature request] Add option to use fixed port for testing

### ISSUE THREAD

**Issue by muink** [ccding/go-stun#46]
Please add option to use fixed port for testing. Instead of random port.
Like this `go-stun -s stun.syncthing.net:3478 -p6789`

**Comment by YTGhost** [comment]
+1

**Comment by muink** [comment]
@YTGhost https://www.stunprotocol.org/ Another project, even better

**Comment by YTGhost** [comment]
> @YTGhost https://www.stunprotocol.org/ Another project, even better

@muink  Thank you very much! This has helped me a lot.
