### ISSUE TITLE
如果能指定物理网卡就更好了

### ISSUE THREAD

**Issue by dmserver** [ccding/go-stun#54]
linux主机接入多个网络 默认随机检测一个
如果能指定物理网卡就更好了

**Comment by xlch88** [comment]
最新的一个版本，添加了一个参数`i`以指定特定的出口ip，你可以先获得网卡的ip以后，用这个参数指定，这样就会测到这个网卡的结果。当然，这需要你自己使用源代码编译，当前已经构建好的release版本并不包含这一更新。
