### ISSUE TITLE
Issues with the STUN test - I cannot identify the NAT type

### ISSUE THREAD

**Issue by ravenrani** [ccding/go-stun#55]
It seems there is a problem with all those tools.
First, I think google were blocking all those calls so one cannot use google's STUN in order to identify anything

This is what I get :
NAT Type: Unexpected response from the STUN server
External IP Family: 1
External IP: ##.###.###.0
External Port: 48150

C:\Users\rani>go-stun -v 3 -s "[20.44.81.178:32000](http://20.44.81.178:32000/)"
2024/10/13 10:29:13 Do Test1
2024/10/13 10:29:13 Send To: [20.44.81.178:32000](http://20.44.81.178:32000/)
2024/10/13 10:29:13
00000000  00 01 00 18 21 12 a4 42  8d e5 bc b2 80 e5 2b ad  |....!..B......+.|
00000010  a9 bd 80 f4 80 22 00 0c  53 74 75 6e 43 6c 69 65  |....."..StunClie|
00000020  6e 74 00 00 80 28 00 04  df 27 df 28              |nt...(...'.(|
2024/10/13 10:29:13
00000000  01 01 00 48 21 12 a4 42  8d e5 bc b2 80 e5 2b ad  |...H!..B......+.|
00000010  a9 bd 80 f4 00 20 00 08  00 01 ac 9e 6c 9b ee 68  |..... ......l..h|
00000020  00 01 00 08 00 01 8d 8c  4d 89 4a 2a 80 2b 00 08  |........M.J*.+..|
00000030  00 01 7d 00 14 2c 51 b2  80 22 00 18 43 6f 74 75  |..}..,Q.."..Cotu|
00000040  72 6e 2d 34 2e 35 2e 32  20 27 64 61 6e 20 45 69  |rn-4.5.2 'dan Ei|
00000050  64 65 72 27 80 28 00 04  f0 08 2f 67              |der'.(..../g|
2024/10/13 10:29:13 Received: {packet nil: false, local: [77.137.74.42:36236](http://77.137.74.42:36236/), remote: [20.44.81.178:32000](http://20.44.81.178:32000/), changed: <nil>, other: <nil>, identical: false}
Error: Server error: no changed address

C:\Users\rani>go-stun -v 3 -s "[stun.stunprotocol.org:3478](http://stun.stunprotocol.org:3478/)"
2024/10/13 10:29:54 Do Test1
2024/10/13 10:29:54 Send To: [127.0.0.1:3478](http://127.0.0.1:3478/)
2024/10/13 10:29:54
00000000  00 01 00 18 21 12 a4 42  69 02 30 b2 01 da 93 ce  |....!..Bi.0.....|
00000010  a1 4f 7d d9 80 22 00 0c  53 74 75 6e 43 6c 69 65  |.O}.."..StunClie|
00000020  6e 74 00 00 80 28 00 04  f2 e0 c8 72              |nt...(.....r|
2024/10/13 10:30:03 Received: Nil
NAT Type: UDP is blocked

it seems like there is no way to get the NAT type.

**Comment by xlch88** [comment]
If you are in certain specific regions (such as Mainland China), please make sure that both the client and server are located in the same country. You can try the following STUN servers:

- stun.miwifi.com:3478
- stun.qwq.pink:3478

The issue of "Server error: no changed address" occurs because the target STUN server does not have two independent IP addresses, and therefore cannot perform the address translation. If this is your self-deployed server, please ensure that the server has at least two public IP addresses.
