### ISSUE TITLE
有没有搭建stunserver的文档

### ISSUE THREAD

**Issue by xingkongwangbin** [ccding/go-stun#56]
# 众所周知go-stun使用的是第三方的stun服务器，如何自建服务器，比如使用stunserver，coturn之类的自建一个服务器

**Comment by xlch88** [comment]
这里不是求现成教程的地方，请您善用搜索引擎或AI，相信您通过自己学习搭建出来一定会更有成就感，加油。

**Comment by xingkongwangbin** [comment]
> 这里不是求现成教程的地方，请您善用搜索引擎或AI，相信您通过自己学习搭建出来一定会更有成就感，加油。

您好，由于我自己搭建的stunserver有问题无法获取nat等级所以才有此一问，这是我搭建的110.252.48.25:3478.如果有文档辛苦可以分享一下，我可以红包感谢

**Comment by xlch88** [comment]
> > 这里不是求现成教程的地方，请您善用搜索引擎或AI，相信您通过自己学习搭建出来一定会更有成就感，加油。
> 
> 您好，由于我自己搭建的stunserver有问题无法获取nat等级所以才有此一问，这是我搭建的110.252.48.25:3478.如果有文档辛苦可以分享一下，我可以红包感谢

https://github.com/ccding/go-stun/issues/55
可以参考这个方式调试，**发出详细的报错信息**，以及，这个issues最后说到的一个重要的事情是**服务器必须有两个公网IP**。
